import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import guestsRouter from "./guests";
import chatRouter from "./chat";
import hotelRouter from "./hotel";
import trackingRouter from "./tracking";
import requestsRouter from "./requests";
import analyticsRouter from "./analytics";
import welcomeAlertRouter from "./welcome-alert";
import staffRouter from "./staff";
import tasksRouter from "./tasks";
import staffPortalRouter from "./staff-portal";
import routineTasksRouter from "./routine-tasks";
import restaurantRouter from "./restaurant";
import folioRouter from "./folio";
import wifiNetworksRouter from "./wifi-networks";
import nearbyPlacesRouter from "./nearby-places";
import guestPreferencesRouter from "./guest-preferences";
import ttsRouter from "./tts";
import assistantConfigRouter from "./assistant-config";
import hotelSetupRouter from "./hotel-setup";
import platformRouter from "./platform";
import platformAuthRouter from "./platform-auth";
import publicHotelsRouter from "./public-hotels";
import publicConfigRouter from "./public-config";
import publicContactRouter from "./public-contact";

const router: IRouter = Router();

router.use(healthRouter);
router.use(publicConfigRouter);
router.use(publicContactRouter);
router.use(publicHotelsRouter);
router.use(platformAuthRouter);
router.use(platformRouter);
router.use(authRouter);
router.use(guestsRouter);
router.use(chatRouter);
router.use(hotelRouter);
router.use(trackingRouter);
router.use(requestsRouter);
router.use(analyticsRouter);
router.use(welcomeAlertRouter);
router.use(staffRouter);
router.use(tasksRouter);
router.use(staffPortalRouter);
router.use(routineTasksRouter);
router.use(restaurantRouter);
router.use(folioRouter);
router.use(wifiNetworksRouter);
router.use(nearbyPlacesRouter);
router.use(guestPreferencesRouter);
router.use(ttsRouter);
router.use(assistantConfigRouter);
router.use(hotelSetupRouter);

export default router;
