// Re-export all TypeScript interface types (generated by orval from OpenAPI)
export * from "./generated/types";

// Re-export Zod validation schemas from generated/api.ts
// Names that are ALSO in ./generated/types (LoginResponse, SendMessageResponse)
// are intentionally omitted here to avoid TS2308 duplicate-export errors.
// All other zod schemas are exported under their original names.
export {
  HealthCheckResponse,
  LoginBody,
  LogoutResponse,
  GetGoogleAuthStatusResponse,
  ExchangeGoogleCodeQueryParams,
  ExchangeGoogleCodeResponse,
  GetMeResponse,
  ListGuestsResponseItem,
  ListGuestsResponse,
  CreateGuestBody,
  GetGuestParams,
  GetGuestResponse,
  CreateChatSessionResponse,
  GetChatMessagesParams,
  GetChatMessagesResponseItem,
  GetChatMessagesResponse,
  SendMessageParams,
  SendMessageBody,
  GetHotelBrandingResponse,
  ListQuickActionsResponseItem,
  ListQuickActionsResponse,
} from "./generated/api";
